name: socket_io
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.2
  get: ^4.6.5
  uuid: ^3.0.7
  chat_bubbles: ^1.4.1
  get_storage: ^2.1.1
  firebase_core: ^2.13.0
  faker: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

